---
version: 2.1

orbs:
  terraform: twdps/terraform@0.4.0

# ==== global pipeline parameters

parameters:
  terraform-version:
    description: terraform version for all jobs
    type: string
    default: "1.0.6"
  context:
    description: circleci context for all jobs
    type: string
    default: twdps-core-labs-team
  shell-options:
    description: shell options for all jobs
    type: string
    default: secrethub run -- /bin/sh -eo pipefail

# git push: release
on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      acct:
        type: string
        default: ''
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.acct >> environment variables
          command: secrethub inject -i environments/<< parameters.acct >>.auto.tfvars.json.tpl -o << parameters.acct >>.auto.tfvars.json

workflows:
  version: 2
  lab-platform-hosted-zones:

    jobs:
      - terraform/plan:
          name: hosted-zone-change-plan
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: state
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                acct: multiaccount
          filters: *on-push-main

      - approve-hosted-zone-changes:
          type: approval
          requires:
            - hosted-zone-change-plan
          filters: *on-push-main

      - terraform/apply:
          name: hosted-zone-change-apply
          context: << pipeline.parameters.context >>
          shell: << pipeline.parameters.shell-options >>
          workspace: state
          terraform-version: << pipeline.parameters.terraform-version >>
          before-terraform:
            - set-environment:
                acct: multiaccount
          requires:
            - approve-hosted-zone-changes
          filters: *on-push-main
