---
version: 2.1

orbs:
  terraform: feedyard/terraform@0.5.0

# git push: release
on-push-master: &on-push-master
  branches:
    only: /master/
  tags:
    ignore: /.*/

commands:

  set-environment:
    description: generate environment credentials and configuration from templates
    parameters:
      account:
        type: string
        default: ''
    steps:
      - run:
          name: set ~/.terraformrc
          command: secrethub inject -i tpl/terraformrc.tpl -o ~/.terraformrc
      - run:
          name: set << parameters.account >> environment variables
          command: secrethub inject -i environments/<< parameters.account >>.auto.tfvars.json.tpl -o << parameters.account >>.auto.tfvars.json

workflows:
  version: 2
  lab-platform-hosted-zones:

    jobs:
      - terraform/plan:
          name: hosted-zone-change-plan
          context: twdps-core-labs-team
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: state
          before-terraform:
            - set-environment:
                account: multiaccount
          filters: *on-push-master

      - approve-hosted-zone-changes:
          type: approval
          requires:
            - hosted-zone-change-plan
          filters: *on-push-master

      - terraform/apply:
          name: hosted-zone-change-apply
          context: twdps-core-labs-team
          shell: secrethub run -- /bin/sh -eo pipefail
          workspace: state
          before-terraform:
            - set-environment:
                account: multiaccount
          after-terraform:
            - run:
                name: test hosted zone configuration
                command: |
                  bash scripts/hosted_zone_test.sh multiaccount nonprod
                  bash scripts/hosted_zone_test.sh multiaccount prod
          requires:
            - approve-hosted-zone-changes
          filters: *on-push-master
